// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OurRadio.Data;

#nullable disable

namespace OurRadio.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("OurRadio.Models.Radio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Radios");
                });

            modelBuilder.Entity("OurRadio.Models.RadioSong", b =>
                {
                    b.Property<int>("RadioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SongId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RadioId", "SongId");

                    b.HasIndex("SongId");

                    b.ToTable("RadioSongs");
                });

            modelBuilder.Entity("OurRadio.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("OurRadio.Models.RadioSong", b =>
                {
                    b.HasOne("OurRadio.Models.Radio", "Radio")
                        .WithMany("RadioSongs")
                        .HasForeignKey("RadioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OurRadio.Models.Song", "Song")
                        .WithMany("RadioSongs")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Radio");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("OurRadio.Models.Radio", b =>
                {
                    b.Navigation("RadioSongs");
                });

            modelBuilder.Entity("OurRadio.Models.Song", b =>
                {
                    b.Navigation("RadioSongs");
                });
#pragma warning restore 612, 618
        }
    }
}
